// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoints.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const lastSnapshot = `-- name: LastSnapshot :one
SELECT id, venue, account_type, taken_at, balance_count, status, error, created_at
FROM snapshot_checkpoints
WHERE venue = $1 AND account_type = $2
ORDER BY taken_at DESC, created_at DESC
LIMIT 1
`

type LastSnapshotParams struct {
	Venue       string
	AccountType string
}

func (q *Queries) LastSnapshot(ctx context.Context, arg LastSnapshotParams) (SnapshotCheckpoint, error) {
	row := q.db.QueryRow(ctx, lastSnapshot, arg.Venue, arg.AccountType)
	var i SnapshotCheckpoint
	err := row.Scan(
		&i.ID,
		&i.Venue,
		&i.AccountType,
		&i.TakenAt,
		&i.BalanceCount,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const recordSnapshot = `-- name: RecordSnapshot :exec
INSERT INTO snapshot_checkpoints (id, venue, account_type, taken_at, balance_count, status, error)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type RecordSnapshotParams struct {
	ID           uuid.UUID
	Venue        string
	AccountType  string
	TakenAt      time.Time
	BalanceCount int32
	Status       string
	Error        string
}

func (q *Queries) RecordSnapshot(ctx context.Context, arg RecordSnapshotParams) error {
	_, err := q.db.Exec(ctx, recordSnapshot,
		arg.ID,
		arg.Venue,
		arg.AccountType,
		arg.TakenAt,
		arg.BalanceCount,
		arg.Status,
		arg.Error,
	)
	return err
}
