// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const decrementLot = `-- name: DecrementLot :exec
UPDATE lots
SET remaining_qty = remaining_qty - $1,
    status = CASE WHEN remaining_qty - $1 = 0 THEN 'closed' ELSE 'open' END,
    closed_at = CASE WHEN remaining_qty - $1 = 0 THEN $2::timestamptz ELSE NULL END
WHERE id = $3
`

type DecrementLotParams struct {
	Qty      decimal.Decimal
	ClosedAt time.Time
	ID       string
}

func (q *Queries) DecrementLot(ctx context.Context, arg DecrementLotParams) error {
	_, err := q.db.Exec(ctx, decrementLot, arg.Qty, arg.ClosedAt, arg.ID)
	return err
}

const insertLot = `-- name: InsertLot :exec
INSERT INTO lots (
    id, bot_id, venue, base, quote, qty, remaining_qty, cost_price,
    opened_by_fill_id, status, opened_at
)
VALUES ($1, $2, $3, $4, $5, $6, $6, $7, $8, 'open', $9)
`

type InsertLotParams struct {
	ID             string
	BotID          string
	Venue          string
	Base           string
	Quote          string
	Qty            decimal.Decimal
	CostPrice      decimal.Decimal
	OpenedByFillID int64
	OpenedAt       time.Time
}

func (q *Queries) InsertLot(ctx context.Context, arg InsertLotParams) error {
	_, err := q.db.Exec(ctx, insertLot,
		arg.ID,
		arg.BotID,
		arg.Venue,
		arg.Base,
		arg.Quote,
		arg.Qty,
		arg.CostPrice,
		arg.OpenedByFillID,
		arg.OpenedAt,
	)
	return err
}

const insertLotClosure = `-- name: InsertLotClosure :exec
INSERT INTO lot_closures (lot_id, sell_fill_id, qty, price, closed_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertLotClosureParams struct {
	LotID      string
	SellFillID int64
	Qty        decimal.Decimal
	Price      decimal.Decimal
	ClosedAt   time.Time
}

func (q *Queries) InsertLotClosure(ctx context.Context, arg InsertLotClosureParams) error {
	_, err := q.db.Exec(ctx, insertLotClosure,
		arg.LotID,
		arg.SellFillID,
		arg.Qty,
		arg.Price,
		arg.ClosedAt,
	)
	return err
}

const insertUnmatchedSell = `-- name: InsertUnmatchedSell :exec
INSERT INTO unmatched_sells (sell_fill_id, bot_id, venue, base, quote, qty, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertUnmatchedSellParams struct {
	SellFillID int64
	BotID      string
	Venue      string
	Base       string
	Quote      string
	Qty        decimal.Decimal
	OccurredAt time.Time
}

func (q *Queries) InsertUnmatchedSell(ctx context.Context, arg InsertUnmatchedSellParams) error {
	_, err := q.db.Exec(ctx, insertUnmatchedSell,
		arg.SellFillID,
		arg.BotID,
		arg.Venue,
		arg.Base,
		arg.Quote,
		arg.Qty,
		arg.OccurredAt,
	)
	return err
}

const listOpenLotsForUpdate = `-- name: ListOpenLotsForUpdate :many
SELECT id, bot_id, venue, base, quote, qty, remaining_qty, cost_price, opened_by_fill_id, status, opened_at, closed_at FROM lots
WHERE bot_id = $1 AND venue = $2 AND base = $3 AND quote = $4 AND status = 'open'
ORDER BY opened_at, id
FOR UPDATE
`

type ListOpenLotsForUpdateParams struct {
	BotID string
	Venue string
	Base  string
	Quote string
}

func (q *Queries) ListOpenLotsForUpdate(ctx context.Context, arg ListOpenLotsForUpdateParams) ([]Lot, error) {
	rows, err := q.db.Query(ctx, listOpenLotsForUpdate,
		arg.BotID,
		arg.Venue,
		arg.Base,
		arg.Quote,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lot
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Venue,
			&i.Base,
			&i.Quote,
			&i.Qty,
			&i.RemainingQty,
			&i.CostPrice,
			&i.OpenedByFillID,
			&i.Status,
			&i.OpenedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInventory = `-- name: LockInventory :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

func (q *Queries) LockInventory(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, lockInventory, key)
	return err
}
