// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type SnapshotCheckpoint struct {
	ID           uuid.UUID
	Venue        string
	AccountType  string
	TakenAt      time.Time
	BalanceCount int32
	Status       string
	Error        string
	CreatedAt    time.Time
}
