// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const adoptVenueOrderID = `-- name: AdoptVenueOrderID :execrows
UPDATE orders
SET venue_order_id = $2,
    updated_at     = now()
WHERE client_order_id = $1 AND venue_order_id IS NULL
`

type AdoptVenueOrderIDParams struct {
	ClientOrderID string
	VenueOrderID  *string
}

func (q *Queries) AdoptVenueOrderID(ctx context.Context, arg AdoptVenueOrderIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, adoptVenueOrderID, arg.ClientOrderID, arg.VenueOrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyOrderUpdate = `-- name: ApplyOrderUpdate :exec
UPDATE orders
SET status         = $2,
    filled_qty     = $3,
    avg_fill_price = $4,
    venue_order_id = COALESCE(venue_order_id, $5),
    reason         = COALESCE($6, reason),
    updated_at     = now()
WHERE client_order_id = $1
`

type ApplyOrderUpdateParams struct {
	ClientOrderID string
	Status        string
	FilledQty     decimal.Decimal
	AvgFillPrice  pgtype.Numeric
	VenueOrderID  *string
	Reason        *string
}

func (q *Queries) ApplyOrderUpdate(ctx context.Context, arg ApplyOrderUpdateParams) error {
	_, err := q.db.Exec(ctx, applyOrderUpdate,
		arg.ClientOrderID,
		arg.Status,
		arg.FilledQty,
		arg.AvgFillPrice,
		arg.VenueOrderID,
		arg.Reason,
	)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT client_order_id, venue, base, quote, venue_symbol, side, type, price, qty, filled_qty, avg_fill_price, status, venue_order_id, bot_id, cancel_requested_at, reason, created_at, updated_at FROM orders WHERE client_order_id = $1
`

func (q *Queries) GetOrder(ctx context.Context, clientOrderID string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, clientOrderID)
	var i Order
	err := row.Scan(
		&i.ClientOrderID,
		&i.Venue,
		&i.Base,
		&i.Quote,
		&i.VenueSymbol,
		&i.Side,
		&i.Type,
		&i.Price,
		&i.Qty,
		&i.FilledQty,
		&i.AvgFillPrice,
		&i.Status,
		&i.VenueOrderID,
		&i.BotID,
		&i.CancelRequestedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT client_order_id, venue, base, quote, venue_symbol, side, type, price, qty, filled_qty, avg_fill_price, status, venue_order_id, bot_id, cancel_requested_at, reason, created_at, updated_at FROM orders WHERE client_order_id = $1 FOR UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, clientOrderID string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, clientOrderID)
	var i Order
	err := row.Scan(
		&i.ClientOrderID,
		&i.Venue,
		&i.Base,
		&i.Quote,
		&i.VenueSymbol,
		&i.Side,
		&i.Type,
		&i.Price,
		&i.Qty,
		&i.FilledQty,
		&i.AvgFillPrice,
		&i.Status,
		&i.VenueOrderID,
		&i.BotID,
		&i.CancelRequestedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFill = `-- name: InsertFill :execrows
INSERT INTO fills (client_order_id, transition_id, qty, price, fee, fee_currency, venue_fill_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (client_order_id, venue_fill_id) WHERE venue_fill_id IS NOT NULL DO NOTHING
`

type InsertFillParams struct {
	ClientOrderID string
	TransitionID  int64
	Qty           decimal.Decimal
	Price         pgtype.Numeric
	Fee           pgtype.Numeric
	FeeCurrency   *string
	VenueFillID   *string
	OccurredAt    time.Time
}

func (q *Queries) InsertFill(ctx context.Context, arg InsertFillParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFill,
		arg.ClientOrderID,
		arg.TransitionID,
		arg.Qty,
		arg.Price,
		arg.Fee,
		arg.FeeCurrency,
		arg.VenueFillID,
		arg.OccurredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPendingOrder = `-- name: InsertPendingOrder :execrows
INSERT INTO orders (client_order_id, venue, base, quote, venue_symbol, side, type, price, qty, bot_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'pending')
ON CONFLICT (client_order_id) DO NOTHING
`

type InsertPendingOrderParams struct {
	ClientOrderID string
	Venue         string
	Base          string
	Quote         string
	VenueSymbol   string
	Side          string
	Type          string
	Price         decimal.Decimal
	Qty           decimal.Decimal
	BotID         string
}

func (q *Queries) InsertPendingOrder(ctx context.Context, arg InsertPendingOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPendingOrder,
		arg.ClientOrderID,
		arg.Venue,
		arg.Base,
		arg.Quote,
		arg.VenueSymbol,
		arg.Side,
		arg.Type,
		arg.Price,
		arg.Qty,
		arg.BotID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTransition = `-- name: InsertTransition :one
INSERT INTO order_transitions (client_order_id, seq, from_status, to_status, filled_qty, source, reason, occurred_at)
VALUES (
    $1,
    (SELECT COALESCE(MAX(seq), 0) + 1 FROM order_transitions WHERE client_order_id = $1),
    $2, $3, $4, $5, $6, $7
)
RETURNING id, seq
`

type InsertTransitionParams struct {
	ClientOrderID string
	FromStatus    string
	ToStatus      string
	FilledQty     decimal.Decimal
	Source        string
	Reason        *string
	OccurredAt    time.Time
}

type InsertTransitionRow struct {
	ID  int64
	Seq int32
}

func (q *Queries) InsertTransition(ctx context.Context, arg InsertTransitionParams) (InsertTransitionRow, error) {
	row := q.db.QueryRow(ctx, insertTransition,
		arg.ClientOrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.FilledQty,
		arg.Source,
		arg.Reason,
		arg.OccurredAt,
	)
	var i InsertTransitionRow
	err := row.Scan(&i.ID, &i.Seq)
	return i, err
}

const listActiveOrders = `-- name: ListActiveOrders :many
SELECT client_order_id, venue, base, quote, venue_symbol, side, type, price, qty, filled_qty, avg_fill_price, status, venue_order_id, bot_id, cancel_requested_at, reason, created_at, updated_at FROM orders
WHERE venue = $1 AND status IN ('pending', 'open', 'partially_filled')
ORDER BY created_at
`

func (q *Queries) ListActiveOrders(ctx context.Context, venue string) ([]Order, error) {
	rows, err := q.db.Query(ctx, listActiveOrders, venue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ClientOrderID,
			&i.Venue,
			&i.Base,
			&i.Quote,
			&i.VenueSymbol,
			&i.Side,
			&i.Type,
			&i.Price,
			&i.Qty,
			&i.FilledQty,
			&i.AvgFillPrice,
			&i.Status,
			&i.VenueOrderID,
			&i.BotID,
			&i.CancelRequestedAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCancelRequested = `-- name: MarkCancelRequested :execrows
UPDATE orders
SET cancel_requested_at = COALESCE(cancel_requested_at, $2),
    updated_at          = now()
WHERE client_order_id = $1
`

type MarkCancelRequestedParams struct {
	ClientOrderID     string
	CancelRequestedAt pgtype.Timestamptz
}

func (q *Queries) MarkCancelRequested(ctx context.Context, arg MarkCancelRequestedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCancelRequested, arg.ClientOrderID, arg.CancelRequestedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
