// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimUnpublishedOutbox = `-- name: ClaimUnpublishedOutbox :many
SELECT id, subject, payload, created_at FROM outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1::bigint
FOR UPDATE SKIP LOCKED
`

type ClaimUnpublishedOutboxRow struct {
	ID        int64
	Subject   string
	Payload   []byte
	CreatedAt time.Time
}

func (q *Queries) ClaimUnpublishedOutbox(ctx context.Context, dollar_1 int64) ([]ClaimUnpublishedOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedOutbox, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimUnpublishedOutboxRow
	for rows.Next() {
		var i ClaimUnpublishedOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOutboxPublishedBefore = `-- name: DeleteOutboxPublishedBefore :execrows
DELETE FROM outbox WHERE published_at IS NOT NULL AND published_at < $1
`

func (q *Queries) DeleteOutboxPublishedBefore(ctx context.Context, publishedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOutboxPublishedBefore, publishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (subject, payload) VALUES ($1, $2)
`

type InsertOutboxParams struct {
	Subject string
	Payload []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.Subject, arg.Payload)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, dollar_1)
	return err
}

const outboxUnpublishedStats = `-- name: OutboxUnpublishedStats :one
SELECT COUNT(*) AS unpublished, COALESCE(MIN(created_at), now())::timestamptz AS oldest
FROM outbox
WHERE published_at IS NULL
`

type OutboxUnpublishedStatsRow struct {
	Unpublished int64
	Oldest      time.Time
}

func (q *Queries) OutboxUnpublishedStats(ctx context.Context) (OutboxUnpublishedStatsRow, error) {
	row := q.db.QueryRow(ctx, outboxUnpublishedStats)
	var i OutboxUnpublishedStatsRow
	err := row.Scan(&i.Unpublished, &i.Oldest)
	return i, err
}
