package ports

import (
	"context"
	"errors"

	"github.com/romanornr/delta-works/internal/domain/order"
)

// ErrNoVenueOrderID reports that a venue-ID lookup was requested without the
// venue identity it requires.
var ErrNoVenueOrderID = errors.New("venue order ID is required")

// OrderPlacer submits and manages orders at a venue. Request.ClientOrderID
// is generated by us and is the idempotency key: retrying PlaceOrder with
// the same ID must not create a second order.
type OrderPlacer interface {
	PlaceOrder(ctx context.Context, req order.Request) (order.Ack, error)
	CancelOrder(ctx context.Context, ref order.Ref) error
	// OpenOrders returns every open order on the venue, unfiltered, so
	// reconciliation sees orders it does not know about.
	OpenOrders(ctx context.Context) ([]order.Snapshot, error)
	// GetOrder returns the venue's current view of the non-empty
	// Ref.VenueOrderID. It returns ErrNoVenueOrderID when that ID is absent.
	GetOrder(ctx context.Context, ref order.Ref) (order.Snapshot, error)
}

// PrivateStreamer streams private order events. The adapter owns
// reconnection; the channel closes only when ctx is canceled. Missed events
// during reconnects are recovered by the reconciliation loop polling
// OpenOrders, not by the stream.
type PrivateStreamer interface {
	StreamOrderEvents(ctx context.Context) (<-chan order.Event, error)
}
