package ports

import (
	"context"

	"github.com/romanornr/delta-works/internal/domain/instrument"
	"github.com/romanornr/delta-works/internal/domain/order"
)

// OrderPlacer submits and manages orders at a venue. No implementor exists
// in M1 — the interface is compiled now to lock the seam order management
// (M2) extends. Request.ClientOrderID is generated by us and is the
// idempotency key: retrying PlaceOrder with the same ID must not create a
// second order.
type OrderPlacer interface {
	PlaceOrder(ctx context.Context, req order.Request) (order.Ack, error)
	CancelOrder(ctx context.Context, ref order.Ref) error
	OpenOrders(ctx context.Context, inst instrument.Instrument) ([]order.Snapshot, error)
}

// PrivateStreamer streams private order events. The adapter owns
// reconnection; the channel closes only when ctx is canceled. Missed events
// during reconnects are recovered by the reconciliation loop polling
// OpenOrders, not by the stream.
type PrivateStreamer interface {
	StreamOrderEvents(ctx context.Context) (<-chan order.Event, error)
}
